export const getDefaultFormData = () => ({
  category: '精油',
  name: '',
  tag: '',
  description: '',

  type: '',
  englishName: '',
  latin: '',
  typePart: '',
  method: '',
  property: '',
  noteAnalogy: '',
  planet: '',
  origin: '',

  constitutionTag: '',
  chemicalTag: '',
  alias: '',
  source: '',
  effect: '',
  indications: '',
  literature: '',
  contraindication: '',
  note: '',
  family: '',
  nature: '',
  meridian: '',
  traits: '',
  dosage: '',
  pharmacology: '',
  contemporary: '',
  medicine: '',
  preparation: '',
  directions: '',
  analysis: '',
  discussion: '',
  syndrome: '',
  modifications: '',
  modernApp: '',
  modernPharmacology: '',
  prescription: '',
  usage: '',
  caution: '',

  acuTable: {
    code: '',
    meridian: '',
    alias: '',
  },

  acuDetails: {
    location: '',
    operation: '',
    indications: '',
    type: '',
    nameExpl: '',
    anatomy: '',
    effectAncient: '',
    effectModern: '',
    matchingPoints: '',
  },

  oilDetails: {
    scent: '',
    appearance: '',
    historyMyth: '',
    chemistry: '',
    attribute: '',
    caution: '',
    mindEffect: '',
    bodyEffect: '',
    skinEffect: '',
    constitution: '',
    blendingOils: '',
    formulas: '',
    carrierOils: '',
    usage: '',
  },

  bookDetails: {
    author: '',
    chapters: [],
  },

  knowledgeDetails: {
    introduction: '',
    sections: [],
  },

  entryKey: '',
  documentId: '',
  firestoreId: '',
  sortName: '',
  searchKey: '',
  sourceText: '',
  createdAt: '',
  updatedAt: '',
});